# Generated by Django 5.2.4 on 2025-07-31 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Helper', 'Helper')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('contact', models.CharField(max_length=15)),
                ('bed_number', models.IntegerField(choices=[(1, 'Bed 1'), (2, 'Bed 2'), (3, 'Bed 3'), (4, 'Bed 4'), (5, 'Bed 5'), (6, 'Bed 6'), (7, 'Bed 7'), (8, 'Bed 8'), (9, 'Bed 9'), (10, 'Bed 10'), (11, 'Bed 11'), (12, 'Bed 12'), (13, 'Bed 13'), (14, 'Bed 14'), (15, 'Bed 15'), (16, 'Bed 16'), (17, 'Bed 17'), (18, 'Bed 18'), (19, 'Bed 19'), (20, 'Bed 20'), (21, 'Bed 21'), (22, 'Bed 22'), (23, 'Bed 23'), (24, 'Bed 24'), (25, 'Bed 25'), (26, 'Bed 26'), (27, 'Bed 27'), (28, 'Bed 28'), (29, 'Bed 29'), (30, 'Bed 30'), (31, 'Bed 31'), (32, 'Bed 32'), (33, 'Bed 33'), (34, 'Bed 34'), (35, 'Bed 35'), (36, 'Bed 36'), (37, 'Bed 37'), (38, 'Bed 38'), (39, 'Bed 39'), (40, 'Bed 40'), (41, 'Bed 41'), (42, 'Bed 42'), (43, 'Bed 43'), (44, 'Bed 44'), (45, 'Bed 45'), (46, 'Bed 46'), (47, 'Bed 47'), (48, 'Bed 48'), (49, 'Bed 49'), (50, 'Bed 50'), (51, 'Bed 51'), (52, 'Bed 52'), (53, 'Bed 53'), (54, 'Bed 54'), (55, 'Bed 55'), (56, 'Bed 56'), (57, 'Bed 57'), (58, 'Bed 58'), (59, 'Bed 59'), (60, 'Bed 60'), (61, 'Bed 61'), (62, 'Bed 62'), (63, 'Bed 63'), (64, 'Bed 64'), (65, 'Bed 65'), (66, 'Bed 66'), (67, 'Bed 67'), (68, 'Bed 68'), (69, 'Bed 69'), (70, 'Bed 70'), (71, 'Bed 71'), (72, 'Bed 72'), (73, 'Bed 73'), (74, 'Bed 74'), (75, 'Bed 75'), (76, 'Bed 76'), (77, 'Bed 77'), (78, 'Bed 78'), (79, 'Bed 79'), (80, 'Bed 80'), (81, 'Bed 81'), (82, 'Bed 82'), (83, 'Bed 83'), (84, 'Bed 84'), (85, 'Bed 85'), (86, 'Bed 86'), (87, 'Bed 87'), (88, 'Bed 88'), (89, 'Bed 89'), (90, 'Bed 90'), (91, 'Bed 91'), (92, 'Bed 92'), (93, 'Bed 93'), (94, 'Bed 94'), (95, 'Bed 95'), (96, 'Bed 96'), (97, 'Bed 97'), (98, 'Bed 98'), (99, 'Bed 99'), (100, 'Bed 100'), (101, 'Bed 101'), (102, 'Bed 102'), (103, 'Bed 103'), (104, 'Bed 104'), (105, 'Bed 105'), (106, 'Bed 106'), (107, 'Bed 107'), (108, 'Bed 108'), (109, 'Bed 109'), (110, 'Bed 110'), (111, 'Bed 111'), (112, 'Bed 112'), (113, 'Bed 113'), (114, 'Bed 114'), (115, 'Bed 115'), (116, 'Bed 116'), (117, 'Bed 117'), (118, 'Bed 118'), (119, 'Bed 119'), (120, 'Bed 120'), (121, 'Bed 121'), (122, 'Bed 122'), (123, 'Bed 123'), (124, 'Bed 124'), (125, 'Bed 125'), (126, 'Bed 126'), (127, 'Bed 127'), (128, 'Bed 128'), (129, 'Bed 129'), (130, 'Bed 130'), (131, 'Bed 131'), (132, 'Bed 132'), (133, 'Bed 133'), (134, 'Bed 134'), (135, 'Bed 135'), (136, 'Bed 136'), (137, 'Bed 137'), (138, 'Bed 138'), (139, 'Bed 139'), (140, 'Bed 140'), (141, 'Bed 141'), (142, 'Bed 142'), (143, 'Bed 143'), (144, 'Bed 144'), (145, 'Bed 145'), (146, 'Bed 146'), (147, 'Bed 147'), (148, 'Bed 148'), (149, 'Bed 149'), (150, 'Bed 150')], unique=True)),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
                ('is_discharged', models.BooleanField(default=False)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_doctor', models.ForeignKey(limit_choices_to={'role': 'Doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.staff')),
            ],
        ),
    ]
